### ISSUE TITLE
Digital IN Pin numbers

### ISSUE THREAD

**Issue by ruedigerO** [hatlabs/HALMET-example-firmware#1]
Which is the right pin numbering for DigitalIn?
Hardware drawing D4 = IO27
HALMET Software example D4 = IO26

**Comment by mairas** [comment]
D3 is IO27 and D4 is IO26. Have a look at the digital input connections on the main page going into the ESP32 block and you'll understand the discrepancy. 🙈

I've just pushed a new version of the design files that make the bug a feature. For your convenience, here's the schematics as PDF:

[HALMET-v1.0.0_fixed.pdf](https://github.com/hatlabs/HALMET-example-firmware/files/13845011/HALMET-v1.0.0_fixed.pdf)

Also, FYI, I'm busy writing the documentation. I think I should have the first partial set online at some point tomorrow.

**Comment by ruedigerO** [comment]
Sorry, I was using a older version of the hardware repository

Thanks for the quick clarification!

**Comment by mairas** [comment]
No, you were right to ask! I hadn't pushed the clarifying changes, so you
had no way of knowing.

**Comment by mairas** [comment]
Closing.
