### ISSUE TITLE
DS18B20 reading 300deg when connected to 

### ISSUE THREAD

**Issue by pmitham** [hatlabs/HALMET-example-firmware#2]
I've connected a DS18B20 temp sensor to the 1 wire header on the board, but when I connect it,  the reading shows 300deg  (299.x)  what could be the issue?  I've used this particular sensor on my Raspberry pi without this issue

Thanks

**Comment by mairas** [comment]
Temperatures in Signal K and in NMEA 2000 or represented in Kelvin. It it the responsibility of the frontend to perform conversion to local units.
